required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/openapi-gen",
  "k8s.io/code-generator/cmd/go-to-protobuf",
  "k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo",
  "k8s.io/gengo/examples/deepcopy-gen",
  "github.com/golang/protobuf/protoc-gen-go",
  "github.com/gogo/protobuf/protoc-gen-gofast",
  "github.com/gogo/protobuf/protoc-gen-gogofast",
  "gopkg.in/src-d/go-git.v4"
]

[[override]]
  branch = "release-1.14"
  name = "k8s.io/api"

[[override]]
  branch = "release-1.14"
  name = "k8s.io/apimachinery"

[[override]]
  branch = "release-11.0"
  name = "k8s.io/client-go"

[[override]]
  name = "github.com/docker/docker"
  branch = "master"

[prune]
  go-tests = true
  unused-packages = true
